version: '3.7'
services:
  postgres:
    volumes:
      - ../postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "8882:5432"
  api:
    ports:
      - 8887:5000
    volumes:
      - .:/app
